sora:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sora
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10

  alioss:
    bucketName: sora-web-app
    endpoint: oss-ap-southeast-2.aliyuncs.com

  wechat:
    appid: wx9f54d547390a2725
    secret: 7d2378eb673a77fdf1ad03d35192143d
